// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXxg9JXmPXu6dUZOwYYKsTQpEQpTvTSzQ',
    appId: '1:890331054042:web:8c10a0d7e1af987c05cae3',
    messagingSenderId: '890331054042',
    projectId: 'zedtutors-app-9c746',
    authDomain: 'zedtutors-app-9c746.firebaseapp.com',
    storageBucket: 'zedtutors-app-9c746.firebasestorage.app',
    measurementId: 'G-EK26RH1J2Y',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9k25bmZOA5YwQ85kWWZgHXrHJmII7Zwo',
    appId: '1:890331054042:ios:8695275b10d84a4505cae3',
    messagingSenderId: '890331054042',
    projectId: 'zedtutors-app-9c746',
    storageBucket: 'zedtutors-app-9c746.firebasestorage.app',
    iosBundleId: 'com.martootechworks.zedtutorsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXxg9JXmPXu6dUZOwYYKsTQpEQpTvTSzQ',
    appId: '1:890331054042:web:e4e3470c7268ff0805cae3',
    messagingSenderId: '890331054042',
    projectId: 'zedtutors-app-9c746',
    authDomain: 'zedtutors-app-9c746.firebaseapp.com',
    storageBucket: 'zedtutors-app-9c746.firebasestorage.app',
    measurementId: 'G-VTWQ2CRPQR',
  );
}
